import { Project } from './types';

export const systemProjects: Project[] = [
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    tagline: 'Command Line Interface',
    role: 'System Tool',
    techStack: ['React', 'TypeScript'],
    description: 'An interactive command-line interface to navigate the portfolio.',
    longDescription: 'Use the terminal to navigate projects, change themes, and learn more about me. Type `help` to see a list of available commands.',
    features: [
      'List and open projects',
      'View project details',
      'Change site theme',
      'View contact info',
      'Clear screen',
    ],
    links: {},
  },
  {
    id: 'login',
    name: 'Login',
    icon: 'Key',
    tagline: 'Admin Access',
    role: 'System Tool',
    techStack: ['React', 'TypeScript', 'Firebase'],
    description: 'System login utility.',
    longDescription: 'Enter credentials to access administrative functions. Uses Firebase Authentication.',
    features: ['Secure login form', 'Session management (Firebase)'],
    links: {},
  },
  {
    id: 'admin-panel',
    name: 'Admin Panel',
    icon: 'Settings',
    tagline: 'Manage Portfolio Content',
    role: 'System Tool',
    techStack: ['React', 'TypeScript', 'Firebase'],
    description: 'A panel to manage portfolio project details in Firestore.',
    longDescription: 'Use this panel to edit the details, media, and links for all portfolio projects. Changes are saved to Firestore.',
    features: ['Edit project text', 'Update image and media links', 'Manage external links', 'Create new projects'],
    links: {},
  },
  {
    id: 'about-me',
    name: 'README.md',
    icon: 'FileText',
    tagline: 'About Me',
    role: 'Author',
    techStack: ['Full-Stack', 'System Architecture', 'AI Integration', 'Blockchain Design'],
    description: 'Information about the author of this portfolio.',
    longDescription: 'This section is populated during the initial setup. If you are seeing this, the setup may not have been completed successfully.',
    features: [
        'Expertise in full-stack development and system architecture.',
        'Integration of complex technologies like AI and blockchain.',
        'A methodical, design-first approach to building scalable systems.',
    ],
    links: {},
  },
];